language: php
php:
- 5.6
- 7.0
- 7.1
sudo: false

services:
  - mysql

branches:
  only:
  - master
  - develop

before_script:
  - mysql -e 'create database ecosystem;'
  - chmod -R 770 storage
  - php artisan migrate:install --no-interaction -vvv

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - php artisan migrate

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit --verbose
  - php artisan migrate:rollback --env=testing --no-interaction -vvv
