language: php
php:
- 5.6
- 7.0
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  
install: travis_retry composer install --no-interaction --prefer-dist
script: vendor/bin/phpunit --verbose
